[project]
name = "turtlesim-pixi"
version = "0.1.0"
description = "ultra fast turtlesim installation on multiple platforms"
authors = ["Ruben Arts <ruben.arts@hotmail.com>"]
channels = ["conda-forge", "robostack-staging"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[commands]
custom_command = "echo hello_world"
turtlesim = "ros2 run turtlesim turtlesim_node"
teleop = "ros2 run turtlesim turtle_teleop_key"

# Custom commands to make using the colcon env easier
build = "colcon build --build-base .pixi/build --install-base .pixi/install --symlink-install"
test = "colcon test --build-base .pixi/build --install-base .pixi/install"
controller = "source .pixi/install/local_setup.sh && ros2 run turtle_controller controller"

[dependencies]
ros-humble-desktop = "0.10.0.*"
ros-humble-turtlesim = "1.4.2.*"
ros-humble-ament-cmake-auto = "*"

colcon-core = "*"
colcon-ros = "*"
