name: Pixi ROS GitHub Actions Demo
on: [push]
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      # Pixi specific setup
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.33.0
          cache: true
      - run: pixi run test